name: Build and Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up build environment
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Run Makefile
        run: make venv all

      - name: Verify executable exists
        run: ls -lh ./dist/aoe_rec_tools.exe

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: ./dist/aoe_rec_tools.exe
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
